[develop]
script_dir=$base/lib/camara_pkg

[install]
install_scripts=$base/lib/camara_pkg

[options]
packages = find:
install_requires =
    setuptools

[options.package_data]
camara_pkg =

[options.entry_points]
console_scripts =
    guidos = camara_pkg.guidos:main
    mqtt_bridge = camara_pkg.mqtt_bridge_node:main

